### ISSUE TITLE
大佬，感谢你的更新，请问能否整合进ndk？

### ISSUE THREAD

**Issue by BRYNHILDRINTHEDARKNESS** [KomiMoe/Arkari#10]
比如说能否将你编译成功的给整合进ndk22 23 24 25

**Comment by KomiMoe** [comment]
因为我是Windows开发，我不了解NDK相关的内容。所以你可以自己试试

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
我尝试移植进ndk25，会出现这种问题
ld: error: unable to find library -latomic
ld: error: unable to find library -l:libunwind.a
ld: error: unable to find library -l:libunwind.a

**Comment by enenH** [comment]
将ndk自带的/lib64/clang文件夹复制一份到/lib/clang可以解决这个问题

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 将ndk自带的/lib64/clang文件夹复制一份到/lib/clang可以解决这个问题

感谢大佬，另外能否提供个联系方式，qq或者tg都可以
