### ISSUE TITLE
llvm17更新啥了呀？

### ISSUE THREAD

**Issue by strawhacker** [KomiMoe/Arkari#13]
给我说下

**Comment by BobH233** [comment]
> [https://intel.github.io/llvm-docs/clang/ReleaseNotes.html](url) (目前来看一般般，并且我在编译内核驱动程序时已经遇到了问题（即使使用官方的rc1无混淆功能版本）。

驱动上有什么坑吗？想避雷一下子

**Comment by BobH233** [comment]
![image](https://github.com/KomiMoe/Arkari/assets/23572936/ea539521-2c86-4856-b157-0a7633b8539c)
不加混淆也加载不上，hhh

**Comment by KomiMoe** [comment]
> ![image](https://user-images.githubusercontent.com/23572936/257433250-ea539521-2c86-4856-b157-0a7633b8539c.png) 不加混淆也加载不上，hhh

蹲一个llvm官方的release吧，估计驱动有点问题。（我还是继续用16

**Comment by BobH233** [comment]
> > ![image](https://user-images.githubusercontent.com/23572936/257433250-ea539521-2c86-4856-b157-0a7633b8539c.png) 不加混淆也加载不上，hhh
> 
> 蹲一个llvm官方的release吧，估计驱动有点问题。（我还是继续用16

嗯，我16编译出来驱动也加载有问题，只有14能用驱动上哈哈哈

**Comment by KomiMoe** [comment]
> > > ![image](https://user-images.githubusercontent.com/23572936/257433250-ea539521-2c86-4856-b157-0a7633b8539c.png) 不加混淆也加载不上，hhh
> > 
> > 
> > 蹲一个llvm官方的release吧，估计驱动有点问题。（我还是继续用16
> 
> 嗯，我16编译出来驱动也加载有问题，只有14能用驱动上哈哈哈

你们可以去研究一下，研究出来之后我去修哦（喵呜~~~嗷呜~~~
