### ISSUE TITLE
 Visual Studio 2022c++命令行参数如何配置？

### ISSUE THREAD

**Issue by helloyw** [KomiMoe/Arkari#15]
请教一下，Visual Studio 2022c++命令行参数如何配置？
`-mllvm -irobf -mllvm --irobf-indbr` 直接这样配置吗？
![image](https://github.com/KomiMoe/Arkari/assets/32027872/9c8d6f87-1c86-42bc-88dc-032f15a23516)

**Comment by ChenZIDu** [comment]
师傅解决了吗，没看懂如何使用= =

**Comment by helloyw** [comment]
> 师傅解决了吗，没看懂如何使用
你可以像我图中那样的配置试试

**Comment by ChenZIDu** [comment]
我看好像需要安装clang
我在看这个博文
https://bbs.kanxue.com/thread-272346.htm

**Comment by ChenZIDu** [comment]
不太懂，怎么将插件加载进vs

**Comment by helloyw** [comment]
> 不太懂，怎么将插件加载进vs

vs 安装clang安装完成后，把这个项目的bin目录文件全拖入到clang的x64\bin目录下就可以了

**Comment by ChenZIDu** [comment]
> 

好的我去试试

**Comment by ChenZIDu** [comment]
师傅，是放到Visual_Studio_2022\VC\Tools\Llvm\x64\bin这个目录吗，clang下面好像没有bin目录

**Comment by ChenZIDu** [comment]
> > 不太懂，怎么将插件加载进vs
> 
> vs 安装clang安装完成后，把这个项目的bin目录文件全拖入到clang的x64\bin目录下就可以了

![image](https://github.com/KomiMoe/Arkari/assets/49174343/5fd82cc8-5b2d-40c6-bd0e-d1ec010df509)
师傅，如果这样显示是失败了吗

**Comment by helloyw** [comment]
> > > 不太懂，怎么将插件加载进vs
> > 
> > 
> > vs 安装clang安装完成后，把这个项目的bin目录文件全拖入到clang的x64\bin目录下就可以了
> 
> ![image](https://user-images.githubusercontent.com/49174343/264601748-5fd82cc8-5b2d-40c6-bd0e-d1ec010df509.png) 师傅，如果这样显示是失败了吗

你这个不太对劲有问题

**Comment by ChenZIDu** [comment]
> 
我把bin文件覆盖到了Visual_Studio_2022\VC\Tools\Llvm\x64\bin这个路径下面
然后配置
![image](https://github.com/KomiMoe/Arkari/assets/49174343/b04752cd-637f-42fb-bc57-f30a6a57362a)

重新生成了解决方案，不过好像是显示忽略未知项，是不是bin文件拷错了，或者拷完bin文件还需要执行什么命令呢

**Comment by ChenZIDu** [comment]
> > > > 不太懂，怎么将插件加载进vs
> > > 
> > > 
> > > vs 安装clang安装完成后，把这个项目的bin目录文件全拖入到clang的x64\bin目录下就可以了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/49174343/264601748-5fd82cc8-5b2d-40c6-bd0e-d1ec010df509.png) 师傅，如果这样显示是失败了吗
> 
> 你这个不太对劲有问题

我把bin文件覆盖到了Visual_Studio_2022\VC\Tools\Llvm\x64\bin这个路径下面
然后配置
![image](https://github.com/KomiMoe/Arkari/assets/49174343/ff3a6e14-2b73-412a-9d92-5bfa2afb9d87)


重新生成了解决方案，不过好像是显示忽略未知项，是不是bin文件拷错了，或者拷完bin文件还需要执行什么命令呢

**Comment by helloyw** [comment]
> > > > > 不太懂，怎么将插件加载进vs
> > > > 
> > > > 
> > > > vs 安装clang安装完成后，把这个项目的bin目录文件全拖入到clang的x64\bin目录下就可以了
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/49174343/264601748-5fd82cc8-5b2d-40c6-bd0e-d1ec010df509.png) 师傅，如果这样显示是失败了吗
> > 
> > 
> > 你这个不太对劲有问题
> 
> 我把bin文件覆盖到了Visual_Studio_2022\VC\Tools\Llvm\x64\bin这个路径下面 然后配置 ![image](https://user-images.githubusercontent.com/49174343/264604282-ff3a6e14-2b73-412a-9d92-5bfa2afb9d87.png)
> 
> 重新生成了解决方案，不过好像是显示忽略未知项，是不是bin文件拷错了，或者拷完bin文件还需要执行什么命令呢

操作对着呢，不需要执行命令

**Comment by ChenZIDu** [comment]
> > > > > > 不太懂，怎么将插件加载进vs不太懂，怎么将插件加载进vs
> > > > > 
> > > > > 
> > > > > vs 安装clang安装完成后，把这个项目的bin目录文件全拖入到clang的x64\bin目录下就可以了vs 安装clang安装完成后，把这个项目的bin目录文件全拖入到clang的x64\bin目录下就可以了
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/49174343/264601748-5fd82cc8-5b2d-40c6-bd0e-d1ec010df509.png)![image](https://user-images.githubusercontent.com/49174343/264601748-5fd82cc8-5b2d-40c6-bd0e-d1ec010df509.png)
> > > 
> > > 
> > > 你这个不太对劲有问题你这个不太对劲有问题
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/49174343/264604282-ff3a6e14-2b73-412a-9d92-5bfa2afb9d87.png)![image](https://user-images.githubusercontent.com/49174343/264604282-ff3a6e14-2b73-412a-9d92-5bfa2afb9d87.png)
> > 重新生成了解决方案，不过好像是显示忽略未知项，是不是bin文件拷错了，或者拷完bin文件还需要执行什么命令呢重新生成了解决方案，不过好像是显示忽略未知项，是不是bin文件拷错了，或者拷完bin文件还需要执行什么命令呢
> 
> 操作对着呢，不需要执行命令
> 
> 操作对着呢，不需要执行命令

师傅要不来个联系方式学习下

**Comment by helloyw** [comment]
>-mllvm -irobf -mllvm --irobf-indbr 修改为这样呢试试

**Comment by helloyw** [comment]
> -mllvm -irobf -mllvm --irobf-indbr 修改为这样呢试试

**Comment by helloyw** [comment]
> ![image](https://user-images.githubusercontent.com/49174343/264609041-88ab6c50-6a8f-482c-aa35-63ebfd2b8069.png)
> 
> > > > > > > 不太懂，怎么将插件加载进vs
> > > > > > 
> > > > > > 
> > > > > > vs 安装clang安装完成后，把这个项目的bin目录文件全拖入到clang的x64\bin目录下就可以了
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/49174343/264601748-5fd82cc8-5b2d-40c6-bd0e-d1ec010df509.png) 师傅，如果这样显示是失败了吗
> > > > 
> > > > 
> > > > 你这个不太对劲有问题
> > > 
> > > 
> > > 我把bin文件覆盖到了Visual_Studio_2022\VC\Tools\Llvm\x64\bin这个路径下面 然后配置 ![image](https://user-images.githubusercontent.com/49174343/264604282-ff3a6e14-2b73-412a-9d92-5bfa2afb9d87.png)
> > > 重新生成了解决方案，不过好像是显示忽略未知项，是不是bin文件拷错了，或者拷完bin文件还需要执行什么命令呢
> > 
> > 
> > 操作对着呢，不需要执行命令
> 
> 是不是要修改这个

-mllvm -irobf -mllvm --irobf-indbr 修改为这样呢试试

**Comment by ChenZIDu** [comment]
好的，我试试
