### ISSUE TITLE
vs2010运行llvm100 添加命令出错

### ISSUE THREAD

**Issue by 929496959** [KomiMoe/Arkari#17]
错误	172	error : error in backend: llvm.eh.recoverfp must take a function as the first argument	
错误	173	error : clang frontend command failed with exit code 70 (use -v to see invocation)	

使用命令：-mllvm -irobf-indbr -mllvm -irobf-icall -mllvm -irobf-indgv -mllvm -irobf-cse -mllvm -irobf-cff 

版本：[Win64-14.0.6-obf1.2.0](https://github.com/KomiMoe/Arkari/releases/tag/Win64-14.0.6-obf1.2.0)

**Comment by KomiMoe** [comment]
请使用vs2019或更新的版本
