### ISSUE TITLE
字符串混淆 -mllvm -irobf-cse 出现了异常

### ISSUE THREAD

**Issue by qiufengshuo** [KomiMoe/Arkari#28]
Windows上开启了字符串加密选项（-mllvm -irobf-cse）后，出现了2个问题。
1.try...catch 语句，catch语句中的字符串未被加密。
2.try...catch 语句，catch语句块中出现了if语句，会导致程序崩溃。
复现示例：
```
#include <iostream>

int main()
{
	int m = 1;
	try
	{
		throw "this is a test";
	}
	catch (const char* p)
	{
		if (m > 0)
			std::cout << "m>0,m:" << m << std::endl;
		else
			std::cout << "m<=0,m:" << m << std::endl;
	}
	catch (const std::exception& ex)
	{
		std::cout << ex.what() << std::endl;
	}
}
```

**Comment by KomiMoe** [comment]
感谢反馈。核实后修复

**Comment by KomiMoe** [comment]
cse是不在EHPad中工作的。字符串加密推荐使用[arkCrypter](https://github.com/KomiMoe/arkCrypter)

**Comment by qiufengshuo** [comment]
issue关闭了，但是，没有issue中的第二条：开启字符串混淆后，try catch 语法中，在catch块中写了if语句，会导致程序崩溃。示例已在issue中贴出。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月20日(周六) 晚上8:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [KomiMoe/Arkari] 字符串混淆 -mllvm -irobf-cse 出现了异常 (Issue #28)




 
Closed #28 as completed via e1e78c4.

**Comment by KomiMoe** [comment]
已核实，未正确修复
