### ISSUE TITLE
"clang-cl.exe" exited with code -1073741819.

### ISSUE THREAD

**Issue by githubuser7355** [KomiMoe/Arkari#34]
I encountered an issue like described in the title while compiling my project using Visual Studio 2022 on Windows 10.
Here's my code:
```
#include <iostream>
int main()
{
    std::cout << "hello, world";
    return 0;
}
```
When I execute clang-cl --version in the terminal, it exits without returning any output. Under the same conditions, running the original clang command returns the following information:
```
clang version 18.1.5
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\LLVM\bin
```
Using the original clang version, I was able to compile my project successfully.

**Comment by KomiMoe** [comment]
```
PS D:\source\Arkari\build_ninja\bin> .\clang-cl --version
clang version 18.1.8 (https://github.com/KomiMoe/Arkari.git e1e78c4ec81304fed18e7df5a39a5b34a6c407bb)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\source\Arkari\build_ninja\bin
```

The information provided is not detailed enough, and the error cannot be reproduced.

**Comment by wyxather** [comment]
anyone facing this issue, instead of replacing bin and lib into your llvm dir, try renaming your original llvm bin to someting else and just move arkari bin to llvm dir and copy the original clang-tidy to arkari bin.

**Comment by KomiMoe** [comment]
You need to upgrade your msvc runtime.
I'll publish next release with msvcrt runtime.
