### ISSUE TITLE
字符串加密bug

### ISSUE THREAD

**Issue by 1136117475** [KomiMoe/Arkari#49]
开启编译优化的情况下，字符串加密仅对开启局部混淆的函数起作用，其他地方的字符串没有被加密。

并且在开启编译优化情况下，只开启字符串加密，仍有大部分字符串没有被加密

设置编译参数为O0，就正常加密了

**Comment by KomiMoe** [comment]
虽然说字符串加密我已经放弃它了。但是还请给出更详细的信息。我这边也去试试重现错误

**Comment by KomiMoe** [comment]
Fixed with #50 Win64-MT-19.1.1-obf1.5.3

**Comment by 1136117475** [comment]
![Screenshot_2024-10-07-11-20-34-934_bin mt plus](https://github.com/user-attachments/assets/407f7ea2-46a0-43a1-9abf-b83e22d39b48)
这是原代码
![Screenshot_2024-10-07-11-21-16-428_bin mt plus](https://github.com/user-attachments/assets/ab9d9f31-2065-40c6-82b7-33f87132359d)
这是编译参数(开编译优化)
![Screenshot_2024-10-07-11-21-44-687_bin mt plus](https://github.com/user-attachments/assets/37b832a2-d1aa-4b56-afcb-c6b9bd5974c3)
这是编译结果，字符串并没有被加密
![Screenshot_2024-10-07-11-22-25-310_bin mt plus](https://github.com/user-attachments/assets/a446e220-9c2f-42d2-a2be-554a7784d78d)
这是编译参数(不开编译优化)
![Screenshot_2024-10-07-11-22-37-363_bin mt plus](https://github.com/user-attachments/assets/5140095c-f5b2-4289-b6dd-323593f69233)
这是编译结果，字符串成功被加密

然后就是如果在编译中开启-mllvm -irobf-indgv，即使开启编译优化字符串也会被加密

**Comment by KomiMoe** [comment]
你去试试新版本。如果还有问题的话你reopen这个issue

**Comment by 1136117475** [comment]
> 你去试试新版本。如果还有问题的话你reopen这个issue

我是手机编译项目的，aarch64，编译一次要3个小时😭一般我等更新几个版本以后才会去编译
