### ISSUE TITLE
字符串加密bug

### ISSUE THREAD

**Issue by 1136117475** [KomiMoe/Arkari#51]
全局变量字符串不会被加密
![Screenshot_2024-10-07-11-48-58-166_bin mt plus](https://github.com/user-attachments/assets/3a0c0f8d-fff3-468e-89e5-8d7a5bf648b8)
![Screenshot_2024-10-07-11-49-19-585_bin mt plus](https://github.com/user-attachments/assets/1b7cac11-790a-45dd-b398-16c1bcdfb22b)
![Screenshot_2024-10-07-11-50-18-296_bin mt plus](https://github.com/user-attachments/assets/49a1b61d-b06c-4b70-a23d-2152abf0e3a5)

**Comment by KomiMoe** [comment]
const char* const str[] = xxxxx;
