### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by enenH** [KomiMoe/Arkari#53]
使用的最新版 编译boots库时
5.      Running pass "simplifycfg<bonus-inst-threshold=1;no-forward-switch-cond;switch-range-to-icmp;no-switch-to-lookup;keep-loops;hoist-common-insts;sink-common-insts;speculate-blocks;simplify-cond-branch;no-speculate-unpredictables>" on function "_ZN5boost7process13basic_pipebufIcNSt6__ndk111char_traitsIcEEED2Ev"
Exception Code: 0xC0000005
 #0 0x00007ff7583ca9bd (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x19da9bd)
 #1 0x00007ff75897db31 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1f8db31)
 #2 0x00007ff758977fe4 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1f87fe4)
 #3 0x00007ff758967a83 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1f77a83)
 #4 0x00007ff75897f630 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1f8f630)
 #5 0x00007ff75897e182 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1f8e182)
 #6 0x00007ff7587d9b51 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1de9b51)
 #7 0x00007ff7587db030 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1deb030)
 #8 0x00007ff7587dac44 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1deac44)
 #9 0x00007ff757412d02 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0xa22d02)
#10 0x00007ff75848c613 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1a9c613)
#11 0x00007ff756dc21d2 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x3d21d2)
#12 0x00007ff757f9e019 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x15ae019)
#13 0x00007ff756dc2a96 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x3d2a96)
#14 0x00007ff757f9db05 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x15adb05)
#15 0x00007ff759779966 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2d89966)
#16 0x00007ff757f9e634 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x15ae634)
#17 0x00007ff7598290c6 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2e390c6)
#18 0x00007ff757f9f574 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x15af574)
#19 0x00007ff7597795e2 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2d895e2)
#20 0x00007ff75848c8b3 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1a9c8b3)
#21 0x00007ff75b0abec1 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x46bbec1)
#22 0x00007ff7597795c2 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2d895c2)
#23 0x00007ff75848c8b3 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1a9c8b3)
#24 0x00007ff758aeae1b (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x20fae1b)
#25 0x00007ff758ae7cb1 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x20f7cb1)
#26 0x00007ff758ae84c2 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x20f84c2)
#27 0x00007ff758fe472f (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x25f472f)
#28 0x00007ff759ed7155 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x34e7155)
#29 0x00007ff759218fa7 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2828fa7)
#30 0x00007ff758fe334a (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x25f334a)
#31 0x00007ff759218e34 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2828e34)
#32 0x00007ff75920240c (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x281240c)
#33 0x00007ff7592a85d4 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x28b85d4)
#34 0x00007ff756ac9849 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0xd9849)
#35 0x00007ff756ac297d (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0xd297d)
#36 0x00007ff7590dd971 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x26ed971)
#37 0x00007ff758859d6a (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x1e69d6a)
#38 0x00007ff7590de040 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x26ee040)
#39 0x00007ff759028902 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2638902)
#40 0x00007ff759028bec (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x2638bec)
#41 0x00007ff75900b1bb (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x261b1bb)
#42 0x00007ff756ac4d9d (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0xd4d9d)
#43 0x00007ff756ad3614 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0xe3614)
#44 0x00007ff75afb4338 (D:\Android\SDK\ndk\28.0.12433566\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe+0x45c4338)
#45 0x00007ffc6c657374 (C:\Windows\System32\KERNEL32.DLL+0x17374)
#46 0x00007ffc6d0dcc91 (C:\Windows\SYSTEM32\ntdll.dll+0x4cc91)

**Comment by KomiMoe** [comment]
请提供更详细的信息，比如编译参数、命令行、boost库版本，以便我更好的复现错误现场
