### ISSUE TITLE
MacOS15，XCode16，IndirectGlobalVariable链接项目时异常

### ISSUE THREAD

**Issue by ta01st** [KomiMoe/Arkari#54]
新建一个app项目，用IndirectGlobalVariable，在链接时报异常：
0  0x1002c847c  __assert_rtn + 72
1  0x1001f0930  mach_o::PointerFormat_DYLD_CHAINED_PTR_64_OFFSET::unauthRebaseIsVmAddr() const + 0
2  0x1001f294c  ___ZN6mach_o13ChainedFixups11buildFixupsENSt3__14spanIKNS_5Fixup10BindTargetELm18446744073709551615EEENS2_IKNS0_17SegmentFixupsInfoELm18446744073709551615EEEyRKNS0_13PointerFormatEjb_block_invoke_2 + 212
3  0x1001f2b58  void mapReduce<std::__1::pair<std::__1::atomic<mach_o::Fixup const*>, std::__1::atomic<mach_o::Fixup const*>>, int>(std::__1::span<std::__1::pair<std::__1::atomic<mach_o::Fixup const*>, std::__1::atomic<mach_o::Fixup const*>>, 18446744073709551615ul>, unsigned long, void (unsigned long, int&, std::__1::span<std::__1::pair<std::__1::atomic<mach_o::Fixup const*>, std::__1::atomic<mach_o::Fixup const*>>, 18446744073709551615ul>) block_pointer, void (std::__1::span<int, 18446744073709551615ul>) block_pointer) + 324
4  0x100226eac  ld::ChainedFixupsEncoder::writeFixupsLinkEditContent(std::__1::span<unsigned char, 18446744073709551615ul>) + 4104
5  0x100274c04  ld::LayoutExecutable::writeToFile(char const*) + 8272
6  0x1002875d4  ld::Linker::run() + 8424
7  0x100213768  main + 1556
ld: Assertion failed: (rebasePtr->target == low56), function writeChainEntry, file ChainedFixups.cpp, line 1257.
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by KomiMoe** [comment]
Clang版本tag=?
Clang编译参数=?
lld版本=？
lld提供方=?
XCode的项目是swift还是什么=?
测试项目编译参数=?
测试项目代码=?
测试项目Target=x86/arm64?
混淆等级=?

**Comment by ta01st** [comment]
Xcode更新到16.1后莫名的又好了。。。

**Comment by Jacky-LinPeng** [comment]
> Xcode更新到16.1后莫名的又好了。。。

你好、你编译好的toolchains可以直接共享给我吗？（自己编译要好久）
我的邮箱：540933120@qq.com 十分感谢
之前Hikari的混淆方案 Xcode15一直报错。。。 一直在找可用的方案...
